//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityProviders.SqlServerProvider
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AppFrameworkEntities : DbContext
    {
        public AppFrameworkEntities()
            : base("name=AppFrameworkEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Org> Orgs { get; set; }
        public virtual DbSet<OrgApp> OrgApps { get; set; }
        public virtual DbSet<OrgAppRole> OrgAppRoles { get; set; }
        public virtual DbSet<OrgAppUser> OrgAppUsers { get; set; }
        public virtual DbSet<OrgAppUserAuthIp> OrgAppUserAuthIps { get; set; }
        public virtual DbSet<OrgAppUserMetadata> OrgAppUserMetadatas { get; set; }
        public virtual DbSet<OrgAppUserRole> OrgAppUserRoles { get; set; }
        public virtual DbSet<OrgGlobalRole> OrgGlobalRoles { get; set; }
        public virtual DbSet<OrgGlobalUserRole> OrgGlobalUserRoles { get; set; }
        public virtual DbSet<OrgRole> OrgRoles { get; set; }
        public virtual DbSet<OrgUser> OrgUsers { get; set; }
        public virtual DbSet<OrgUserRole> OrgUserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRefreshToken> UserRefreshTokens { get; set; }
    }
}
