//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IdentityProviders.SqlServerProvider
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRefreshToken
    {
        public System.Guid Id { get; set; }
        public string Username { get; set; }
        public string AccessToken { get; set; }
        public System.DateTimeOffset ExpirationDateUtc { get; set; }
        public System.DateTimeOffset IssuedDateUtc { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dt { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_dt { get; set; }
    }
}
