//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mfcu.Repositories.AppFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class DocumentUpload
    {
        public DocumentUpload()
        {
            this.UploadChunks = new HashSet<UploadChunk>();
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public string Status { get; set; }
        public string Description { get; set; }
        public int TotalUploadChunks { get; set; }
        public long FileSize { get; set; }
        public string LaterArchivePath { get; set; }
        public bool IsDeleted { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dt { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_dt { get; set; }
    
        public virtual ICollection<UploadChunk> UploadChunks { get; set; }
    }
}
