//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mfcu.Repositories.AppFramework
{
    using System;
    using System.Collections.Generic;
    
    public partial class UploadChunk
    {
        public int Id { get; set; }
        public string Status { get; set; }
        public string ChunkName { get; set; }
        public int DocumentId { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dt { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_dt { get; set; }
    
        public virtual DocumentUpload Document { get; set; }
    }
}
