//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mfcu.Repositories.ITGov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Assignment
    {
        public int PracticeID { get; set; }
        public int SystemUserID { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dt { get; set; }
    
        public virtual Practice Practice { get; set; }
        public virtual SystemUser SystemUser { get; set; }
    }
}
