//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mfcu.Repositories.ITGov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        public int DocumentID { get; set; }
        public int IncidentTrackingID { get; set; }
    
        public virtual Tracking Tracking { get; set; }
    }
}
