//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mfcu.Repositories.ITGov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int CommentID { get; set; }
        public string Comment1 { get; set; }
        public Nullable<int> CobitPracticeID { get; set; }
        public Nullable<int> IncidentTrackingID { get; set; }
        public bool boolDeleted { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dt { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_dt { get; set; }
    
        public virtual Practice Practice { get; set; }
        public virtual Tracking Tracking { get; set; }
    }
}
