//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mfcu.Repositories.ITGov
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoreSystem
    {
        public CoreSystem()
        {
            this.Trackings = new HashSet<Tracking>();
        }
    
        public int SystemID { get; set; }
        public string SystemDescr { get; set; }
        public Nullable<int> VendorID { get; set; }
        public bool boolIsActive { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dt { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_dt { get; set; }
    
        public virtual Vendor Vendor { get; set; }
        public virtual ICollection<Tracking> Trackings { get; set; }
    }
}
