//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mfcu.Repositories.ITGov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.TrackingDepartments = new HashSet<TrackingDepartment>();
            this.SystemUsers = new HashSet<SystemUser>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentDescr { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<int> CostCenterNumber { get; set; }
        public bool boolIsActive { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dt { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_dt { get; set; }
    
        public virtual ICollection<TrackingDepartment> TrackingDepartments { get; set; }
        public virtual ICollection<SystemUser> SystemUsers { get; set; }
    }
}
