//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mfcu.Repositories.ITGov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Practice
    {
        public Practice()
        {
            this.Assignments = new HashSet<Assignment>();
            this.Comments = new HashSet<Comment>();
            this.Links = new HashSet<Link>();
        }
    
        public int PracticeID { get; set; }
        public string PracticeCode { get; set; }
        public string PracticeName { get; set; }
        public string PracticeDescr { get; set; }
        public string Certification { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public int ProcessID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> CompletionDateTimeStamp { get; set; }
        public bool boolIsActive { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dt { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_dt { get; set; }
    
        public virtual ICollection<Assignment> Assignments { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual ICollection<Link> Links { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Process Process { get; set; }
        public virtual Status Status { get; set; }
    }
}
