//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mfcu.Repositories.ITGov
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tracking
    {
        public Tracking()
        {
            this.Attachments = new HashSet<Attachment>();
            this.Comments = new HashSet<Comment>();
            this.TrackingDepartments = new HashSet<TrackingDepartment>();
        }
    
        public int IncidentTrackingID { get; set; }
        public string IncidentCode { get; set; }
        public string IncidentType { get; set; }
        public Nullable<System.DateTime> IncidentDate { get; set; }
        public Nullable<System.DateTime> DowntimeStart { get; set; }
        public Nullable<System.DateTime> DowntimeEnd { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public string IncidentDescr { get; set; }
        public string CauseDescr { get; set; }
        public string PreventionControlDescr { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> SystemID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public string ResolutionDescr { get; set; }
        public bool boolDeleted { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dt { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_dt { get; set; }
        public Nullable<int> StatusID { get; set; }
    
        public virtual ICollection<Attachment> Attachments { get; set; }
        public virtual ICollection<Comment> Comments { get; set; }
        public virtual SystemUser SystemUser { get; set; }
        public virtual ICollection<TrackingDepartment> TrackingDepartments { get; set; }
        public virtual IncidentStatus Status1 { get; set; }
        public virtual CoreSystem System { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
