//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mfcu.Repositories.ITGov
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPracticeAssignment
    {
        public int PracticeID { get; set; }
        public Nullable<int> SystemUserID { get; set; }
        public string DomainLogin { get; set; }
        public string UserName { get; set; }
        public string EmailAddress { get; set; }
    }
}
