//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mfcu.Repositories.ITGov
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwPractice
    {
        public string AreaDescr { get; set; }
        public string DomainDescr { get; set; }
        public string ProcessCode { get; set; }
        public string ProcessName { get; set; }
        public string ProcessDescr { get; set; }
        public string ProcessPurposeStatement { get; set; }
        public string PracticeCode { get; set; }
        public string PracticeName { get; set; }
        public string PracticeDescr { get; set; }
        public string Certification { get; set; }
        public string OwnerName { get; set; }
        public string OwnerEmailAddress { get; set; }
        public string StatusDescr { get; set; }
        public string PriorityDescr { get; set; }
        public string AssignedSystemUser { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<System.DateTime> CompletionDate { get; set; }
        public Nullable<System.DateTime> CompletionDateTimeStamp { get; set; }
        public bool boolHasDocLink { get; set; }
        public bool boolHasComment { get; set; }
        public int AreaID { get; set; }
        public int DomainID { get; set; }
        public int ProcessID { get; set; }
        public int PracticeID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> StatusID { get; set; }
        public Nullable<int> PriorityID { get; set; }
        public string AssignedSystemUserID { get; set; }
    }
}
