//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mfcu.Repositories.ITGov
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwSystemUser
    {
        public string DomainLogin { get; set; }
        public string UserName { get; set; }
        public string EmailAddress { get; set; }
        public string DepartmentDescr { get; set; }
        public string DepartmentCode { get; set; }
        public Nullable<int> CostCenterNumber { get; set; }
        public bool boolIsCobitOwner { get; set; }
        public bool boolIsIncidentOwner { get; set; }
        public bool boolIsActive { get; set; }
        public int SystemUserID { get; set; }
        public int DepartmentID { get; set; }
    }
}
