//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mfcu.Repositories.ITGov
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwTracking
    {
        public string IncidentCode { get; set; }
        public string IncidentType { get; set; }
        public Nullable<System.DateTime> IncidentDate { get; set; }
        public Nullable<System.DateTime> DowntimeStart { get; set; }
        public Nullable<System.DateTime> DowntimeEnd { get; set; }
        public Nullable<System.DateTime> ResolvedDate { get; set; }
        public string IncidentDescr { get; set; }
        public string CauseDescr { get; set; }
        public string PreventionControlDescr { get; set; }
        public string VendorDescr { get; set; }
        public string SystemDescr { get; set; }
        public string OwnerName { get; set; }
        public string OwnerEmailAddress { get; set; }
        public string OwnerDepartmentDescr { get; set; }
        public string OwnerDepartmentCode { get; set; }
        public string DepartmentsImpacted { get; set; }
        public string StatusDescr { get; set; }
        public string ResolutionDescr { get; set; }
        public bool boolHasComment { get; set; }
        public bool boolHasAttachment { get; set; }
        public string Attachments { get; set; }
        public string created_by { get; set; }
        public System.DateTime created_dt { get; set; }
        public string modified_by { get; set; }
        public System.DateTime modified_dt { get; set; }
        public int IncidentTrackingID { get; set; }
        public Nullable<int> VendorID { get; set; }
        public Nullable<int> SystemID { get; set; }
        public Nullable<int> OwnerID { get; set; }
        public Nullable<int> StatusID { get; set; }
    }
}
